# default
spring:
  profiles:
    active: local
---
spring:
  sql:
   init:
    mode: never
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_web
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  mvc:
    hiddenmethod:
      filter:
        enabled: true
management:
  server:
    port: 8080
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*" #엔드포인트 기능을 액추에이터에 노출시키겠다는것
server:
  tomcat:
    mbeanregistry:
      enabled: true #tomcat 메트릭
logging:
  level:
    root: INFO
    #Redis에 저장된 로그 정보를 볼수 있도록 해준다.
    org.springframework.cache: trace

springdoc:
  swagger-ui:
    tags-sorter: alpha  # 태그 이름 기준 알파벳(숫자 포함) 정렬

slack:
  webhook:
    url: https://hooks.slack.com/services/slackaddress

payment:
  imp:
    key: ${PAYMENT_IMP_KEY}
    secret: ${PAYMENT_IMP_SECRET}

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2